apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-kafka
  template:
    metadata:
      labels:
        app: my-kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.5
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://my-kafka:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: my-kafka
spec:
  selector:
    app: my-kafka
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP
