name: Build & Push Docker Images

on:
  push:
    tags:
      - "v*.*.*"   # only build images for releases

permissions:
  contents: read
  packages: write   # required for GHCR

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # USER SERVICE
      - name: Build & Push user-service
        uses: docker/build-push-action@v5
        with:
          context: ./user-service    # This location should be Dockerfile for user service from where docker image build
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/user-service:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/user-service:latest

      # ORDER SERVICE
      - name: Build & Push order-service
        uses: docker/build-push-action@v5
        with:
          context: ./order-service    # This location should be Dockerfile for order service from where docker image build
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/order-service:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/order-service:latest
